{% set version = "0.15" %}

package:
  name: otmixmod
  version: {{ version }}

source:
  fn: otmixmod-{{ version }}.tar.gz
  url: https://github.com/openturns/otmixmod/archive/v{{ version }}.tar.gz
  sha256: 81166be1c8d2056911f8ec8e4be056ae2967bd3a7b710b0e8eb6a7ba74bbd3d1

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('otmixmod', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.21*
  run:
    - python
    - openturns 1.21*

test:
  imports:
    - otmixmod

about:
  home: http://openturns.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: MixMod module

extra:
  recipe-maintainers:
    - jschueller
