{% set version = "0.6" %}
{% set ot_version = "1.11rc1" %}

package:
  name: otmixmod
  version: {{ version }}

source:
  fn: otmixmod-{{ version }}.tar.gz  # [not win]
  url: https://github.com/openturns/otmixmod/archive/v{{ version }}.tar.gz  # [not win]
  sha256: 72737abeb8db8fb36762596fdb3fc0b4560035d5080c5593f9b09466edbbc2e9  # [not win]

  fn: otmixmod-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmixmod-{{ version }}-py2.7-x86_64.exe  # [win64 and py27]
  sha256: d8c0796824b48c42804f7d1570c2861d5cdc7169d2eb8b2d51fe528eab49ecb5  # [win64 and py27]

  fn: otmixmod-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmixmod-{{ version }}-py3.5-x86_64.exe  # [win64 and py35]
  sha256: 8aeca86cb0d3f069501010bd1bcefa0d14cd0a64fe5c23a36c416eeb47d03ca2  # [win64 and py35]

  fn: otmixmod-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  url: https://github.com/openturns/build-modules/releases/download/v{{ ot_version }}/otmixmod-{{ version }}-py3.6-x86_64.exe  # [win64 and py36]
  sha256: 908d9a102b2ce4b7725a4a13aa6ab5bea0f18d984b84e8cce2ea9a98b2f8380e  # [win64 and py36]

build:
  number: 1

requirements:
  build:
    - cmake  # [not win]
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
  host:
    - python
    - swig  # [not win]
    - openturns  # [not win]
  run:
    - python
    - openturns

test:
  imports:
    - otmixmod

about:
  home: http://openturns.org/
  license: LGPL3
  #license_file: COPYING.LESSER  # [not win]
  summary: MixMod module

extra:
  recipe-maintainers:
    - jschueller
