{% set version = "0.20" %}

package:
  name: otmixmod
  version: {{ version }}

source:
  fn: otmixmod-{{ version }}.tar.gz
  url: https://github.com/openturns/otmixmod/archive/v{{ version }}.tar.gz
  sha256: aab968bbf9a233db25ed5ccd5b1b05d478e731287d8d85bd09119ca4b459ade2
  patches:
    - 0001-Export-symbols.patch

build:
  number: 2
  run_exports:
    - {{ pin_subpackage('otmixmod', max_pin='x.x') }}
  python_version_independent: true  # [is_abi3]
  skip: True  # [is_abi3 and not is_python_min]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python-abi3  # [is_abi3]
    - python
    - libmixmod
    - openturns
  run:
    - python

test:
  requires:
    - abi3audit  # [is_abi3]
  imports:
    - otmixmod
  commands:
    - abi3audit $SP_DIR/otmixmod/_otmixmod.so -s -v --assume-minimum-abi3 3.10  # [unix and is_abi3]

about:
  home: http://openturns.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: MixMod module

extra:
  recipe-maintainers:
    - jschueller
