{% set version = "0.12" %}

package:
  name: otmixmod
  version: {{ version }}

source:
  fn: otmixmod-{{ version }}.tar.gz
  url: https://github.com/openturns/otmixmod/archive/v{{ version }}.tar.gz
  sha256: 1e1cb2fc10eb5603f4b3e7c78b0056890d4cfd39fc6c7606f0fdb7715c70dd66

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('otmixmod', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl  # [win]
  host:
    - python
    - openturns 1.18*
  run:
    - python
    - openturns 1.18*

test:
  imports:
    - otmixmod

about:
  home: http://openturns.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: MixMod module

extra:
  recipe-maintainers:
    - jschueller
