appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: b1Fhl3a1bihzPdQ4qfXc2u0Pn9pIuT581BGjAN60OWJZBs0fa7LTyjDH4NFrLocgvG6eIiCQfHlBfEy45oXD+RV6Iy8l2Ati24bBhdQk/91LEwAg0pe+a0N3xqRUsz06wvaZK3hj1ZrgQ8+UqBRS9idAmnjqYHaVYvfhiYA05aJj3pd+YC6VrjaMmqG0yCZmcKTHunjFWz6o0LoXUvOO5r4Ovio3fsU/Tee4+1I2gmRDf9t55jevkJKIS9HwsSWzZD179YfKSVqkhitUjvKETNOrtkdHDjWcRGxqFyWEjnAWJZm0Og91VY3bRh5aPG0W39uz/SjfBUABV7xH+tI+hFof+E2kS8drrv/0vcka8nPjFnawHljy7r4RaYGUFm7FQN4cA5bR43iE1d4ta/TV8uBSnU7g7svQwMcOmHXdQ2uBolFi1td6+MMrGRwM5sGar3WTudYYHdKyU/DXgrMvjIS9s52YV0r+U1M/CVL9Fr7Vmq0db40l1BrntkrmqV/qhgK7uZ3Y6XjKv2HUTRjSesdYJxof3yLmtheFg6SwUNiNwGUTjXepTF4/C2hhUzB/zs3DO5Bfw/yuPORAzASwhdfQWLK8aury0t8kOhf8kswOTXNisFcVMVqJR1wWeO9WMko8HFDXKQE9knKJq7RvnvyoKVsFEV7GnhDtUZ+YsTc=}
provider:
  win: azure
