travis:
  secure:
    BINSTAR_TOKEN: Y162Ow19PORWSHVaxS7c0fyHJ0pJ7D1Nxqt2AET/g6oel67QyOXHOlbuhPh8B6L3uv+UVKiOQwrToPfFUcLYq/ij8C8KdcOa8whQV8Iti/0EFA3jemLxI7hSyykbO9hxY97GgYtyAT7FrNDZTb0d/AIuSRwwLSzRQrM0jiK6nGn98/8hGy9JpwtXU9cfozd16K6Q5r0RM1NHZVZOL4Sh4+kmKC++/vk7pyKdXN1nf9XulvJNzKuDWqQDSZzRj5PAJKs8sFcRF8W7nUeY5BBQ1pka7HB48dCPu0QMCA4AXgM20boEzft7r5zq+7DqGBe8umII4xHTuGpdRGtF8XEOAzqyVIlE9izIeR2AVNSGDsHMGdZjhTAXkODiyDwFil3Hi+XNxupt/oQhXrRjUaZItvZIDv4jg/VmBCjwTsOqsE08cL4vBruTAOoMl6MFmh/SECp0iXxnYaI5deeqMGURIIj2TL3O8BMX+XmJFOqd8CbZ4nrLRdtOSb2TsmWiiM0EhcyOwSRHi4UHDtZAp6MVwLZ2T6ejqSBaNOxUes8ksniQdx6JI682dmu3tRcKshwVQeWgud6Pkj1T9f90GUW21MgREJNuTh+b848liqrVaRcr9+VJDB8ClMovdh2MT42QWeIU1sAXmiBGA+z42FcWUQ1dHNZXWsI+wazGpCxktuE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
